export const objTypes = [
    {id: 11, type: 'water', typePtbr: 'água', color: '#6990f1'},
    {id: 16, type: 'dragon', typePtbr: 'dragão', color: '#7039f9'},
    {id: 13, type: 'electric', typePtbr: 'elétrico', color: '#f9d031'},
    {id: 18, type: 'fairy', typePtbr: 'fada', color: '#ed978f'},
    {id: 8, type: 'ghost', typePtbr: 'fantasma', color: '#705898'},
    {id: 10, type: 'fire', typePtbr: 'fogo', color: '#f08131'},
    {id: 15, type: 'ice', typePtbr: 'gelo', color: '#99d9d8'},
    {id: 7, type: 'bug', typePtbr: 'inseto', color: '#a8b820'},
    {id: 2, type: 'fighting', typePtbr: 'lutador', color: '#c03028'},
    {id: 9, type: 'steel', typePtbr: 'metal', color: '#b8b8d0'},
    {id: 1, type: 'normal', typePtbr: 'normal', color: '#a9a978'},
    {id: 6, type: 'rock', typePtbr: 'pedra', color: '#cda530'},
    {id: 12, type: 'grass', typePtbr: 'planta', color: 'green'},
    {id: 14, type: 'psychic', typePtbr: 'psíquico', color: '#f85888'},
    {id: 17, type: 'dark', typePtbr: 'sombrio', color: '#715948'},
    {id: 5, type: 'ground', typePtbr: 'terra', color: '#e0c169'},
    {id: 4, type: 'poison', typePtbr: 'venenoso', color: '#9a3a91'},
    {id: 3, type: 'flying', typePtbr: 'voador', color: '#a990f1'},
];